# Generated by Django 3.2.9 on 2021-11-26 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('body', models.TextField()),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Starts at')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Finishes in')),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Meduim'), ('H', 'High')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['done', '-start_time'],
            },
        ),
    ]
